### ISSUE TITLE
Ongoing: labelling improve feature request. issue triaging and management.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1700]
#### **Feature requests:**

Should be labelled by **all** Team members as a feature request, and if applicable its ok to apply a component label.
#### **Bug reports:**

Labelled by **all** Team members accordingly it helps triaging and managing such things
### About this Post

Ill leave this here to allow valued team feedback, hoping you all dont keep silent else in two weeks or so Ill start implementing this as it seems a no brainer.
###### Rationale for (**Dont use** **KVIrc version** and **priority labels** on feature requests)

According to https://github.com/kvirc/KVIrc/wiki#bugreport-ticket

> If you're going to ask for a new feature, please remember that we're going to implement feature requests only in the next 4.3 version, so any feature request created will be automatically re-targeted to KVIrc 4.3.

**I presume from that statement and looking though all feature requests history 4.3 **Version** automatically means the current/next development version for KVIrc for those requests that dont get implemented**.

**There are features requests going back to stone-age** and this tells me **devs implement what they want whenever they like and have time for.**. So **priority** is largely **irrelevant in the whole**.

It would be OK for instance to add other relevant labels if they are immutable like component/or type e.g. addon/core/gui/modules etc...
#### **Todo list:** (Feel free to add to this list or place checkmarks  if you find anything changed)
- [ ] Review Bug reports / Feature requests **(ongoing - semi regularly basis)**
- [x] Merge duplicates into first report (make notes and label) and close duplicates (ongoing - semi regularly basis)
- [X] Assign bugs/feature request to whoever was assigned on SVN (apparently wodim dislikes this / everything to do with labeling triaging?)
- [X] Test bugs (Linux/Windows) and close after some time if they are fixed in current dev version.
- [X] Ask for feedback on bugs/feature requests from team members
- [X] **Dont use** KVIrc version and priority labels on feature requests and (reason below)
- [ ] [Review labeling categories](https://github.com/kvirc/KVIrc/issues/1700#issuecomment-231216029) and implement in all repos.**(work in progress)**
- [ ] Other, read feedback, work in progress.
#### **Deprecation Notices:**

**Priority labeling changes** prio high/medium/low labels has been deprecated you have crash/security labels instead where applicable

This is because these priority labels make no sense from a triaging point of view **unless a developer that is assigned some tickets then adds these priority labels himself to reflect his/hers plans, since this doesn't happen either** they are irrelevant to the project and have been substituted or removed entirely

**Comment by DarthGandalf** [comment]
There is one issue with github labels: only the elite with access can change them.
If someone just files a bug, he can't select any labels.

**Comment by un1versal** [comment]
Thats a limitation reserved for team members and collaborators, imo its right.

From our side, I find having read though all issues/feature requests that we are relabeling feature requests to reflect the latest dev version when thats automatically assumed to be somewhat futile and I wanted to get feedback on what others think before implementing it in all existing reports.

**Comment by un1versal** [comment]
@HelLViS69 @DarthGandalf @ctrlaltca (you're the guys that I mostly need feedback from) and and all other team members..

Ive finished my review of all issues —bug reports and features requests.

Ive closed many mostly duplicates which have been merged with earliest report for same issue.

The feature requests Ive removed KVIrc version and priority:normal since they are always assumed to be for current development version and have really no priority for implementation, since its up to whoever time/patience/interest, this can take 1 minute or 1 year +++

I hope this helps you guys taking care of the real work, let me know if thers anything you guys would like done in that area.

**Comment by DarthGandalf** [comment]
Thanks!

2015-11-04 9:39 GMT+00:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
Ive continued on a semi regular basis to review all open tickets and retesting some.

I know this is annoying spam wise on IRC channel from **Notificos bot** but there's no middle ground on these hooks for labeling only. disabling labeling notifications means disabling other important stuff.
 So to everyone on #kvirc remember this and thank you for understanding if you dont like this noise ignore the bot.

**Comment by un1versal** [comment]
Can all team member's that open tickets or PR's (or find tickets/PR's unlabelled) please label them...

**Comment by un1versal** [comment]
Labels have been redone 3 have been eliminated @cybershadow wanted to reorganize them into more manageable lot, so in true teamwork fashion, he went and did a list and I implemented the idea.

We could potentially get rid of platform/version labels **but people have to provide minimal details in tickets** legacy tickets could be dammed to hell, after 10 years I feel an itch to close them since its unlikely they will be releavant to anyone fixing them and you cant get in contact with these people anymore.

here are the changes

#### Version:

  4.1 Equilibrium
  4.2.0 Equilibrium
  4.3.2 Aria
  5.0.0 Aria

#### Component:

  3rd Party
  Addon System
  ~~Build System~~
  CI: Travis / Appveyor
  Core
  DCC
  GUI
  Installer
  IRC Protocol
  IRC Servers
  KVS Engine
  Modules
  Translation
  ~~Website~~

#### Severity:

  Bug
  Cleanup
  Crash
  Compiling
  Documentation
  Enhancement
  Feature Request
  Fix
  Refactor
  Security Issue

#### Status:

  Confirmed
  Fixed
  Help Needed / Wanted
  Duplicate
  In Progress (renamed) -> Under Development 
  Incomplete
  Invalid
  Needs Developer Attention -> renamed Needs Developer Feedback
  ~~Needs Team Feedback~~
  Needs User Feedback
  WIP  DO NOT MERGE
  Wont Fix
  Workaround posted
  Works for Me

#### Platform:

  Windows
  Linux
  OS X
  Qt4.x
  Qt5.x
  KDE

**Comment by un1versal** [comment]
I will no longer triage or make any effort to label, manage any labeling or issues belonging to any associated developers or users, be that for feature requests, bug reports or pull requests.

Ive tried and tbh Ive better things to do.

next!
